<?xml version="1.0"?>
<package format="3">

  <name>jaime_behaviour_trees</name>
  <version>0.0.1</version>
  <description>Behaviour Trees for Jaime</description>

  <maintainer email="you@example.com">Jaime</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>py_trees</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>nav2_msgs</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>jaime_interfaces</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>

</package>
