dynamixel_node:
  ros__parameters:

    # Ganancias proporcionales para control de pose
    # [joint_1, joint_2, tablet]
    Kp:
      - -6.0
      - 6.0
      - 4.0

    # Límites máximos de velocidad para control de pose
    # [joint_1, joint_2, tablet]
    vel_limits:
      - 0.5
      - 0.5
      - 0.4
    # ==========================================
    # Límites articulares
    # [l3_to_l2, l4_to_l3, l5_to_l4, l6_to_l5, l7_to_l6]
    # ==========================================
    lower_limits:
      - -0.12
      - 0.48
      - 0.42
      - -0.03
      - -0.72

    upper_limits:
      - 0.43
      - 0.93
      - 0.75
      - 0.31
      - 0.55